---
- hosts: localhost
  become: true
  tasks:
  - name: Check kernel config 
    command: diff .config /usr/src/linux/.config 
    failed_when: "diff_output.rc > 1"
    register: diff_output

  - name: Get cksum of my First file
    stat:
      path : ".config"
    register: myfirstfile
  
  - name: Current SHA1
    set_fact:
      mf1sha1: "{{ myfirstfile.stat.checksum }}"
  
  - name: Get cksum of my Second File (If needed you can jump this)
    stat:
      path : "/usr/src/linux/.config"
    register: mysecondfile
  
  - name: Current SHA1
    set_fact:
      mf2sha1: "{{ mysecondfile.stat.checksum }}"
  
  - name: Compilation Changed
    debug:
      msg: "File Compare"
    failed_when:  mf2sha1 != mf1sha1

#  - debug:
#      var: diff_output
#    command: which equery
#    check_mode: no
#    changed_when: False
#    failed_when: False
#    register: gentoo_portage__register_equery
#  
#  - name: Install gentoolkit for equery support
#    command: emerge --quiet-build=y gentoolkit
#    when: gentoo_portage__register_equery.rc != 0
#
#  - name: copy package.accept_keywords 
#    copy:
#      src: ./package.accept_keywords
#      dest: /etc/portage
#
#  - name: copy package.use 
#    copy:
#      src: ./package.use
#      dest: /etc/portage
#
#  - name: managing gentoo package
#    portage:
#      package: "{{ item }}"
#      state: present
#      newuse: yes
#      verbose: yes
#    with_lines: cat world
#  
