---
- hosts: localhost
  become: true
  tasks:

    #- name: get cpu flags 
    #  shell: "cpuid2cpuflags | sed 's/: /=\"/;s/$/\"/'"
    #  register: cpuflags

    #- name: update make.conf - cpu flags 
    #  lineinfile:
    #    path: /etc/portage/make.conf
    #    regexp: '^CPU_FLAGS_X86='
    #    line: "{{ cpuflags.stdout }}"
  
  - name: enable bluetooth
    systemd:
      name: bluetooth
      enabled: yes

  - name: set keyboard for X11
    shell: localectl set-x11-keymap ch pc105 de_nodeadkeys terminate:ctrl_alt_bksp 
