---
- hosts: localhost
  tasks:
  - name: copy package.accept_keywords 
    copy:
      src: ./package.accept_keywords
      dest: /etc/portage

  - name: copy package.use 
    copy:
      src: ./package.use
      dest: /etc/portage

  - name: copy package.license 
    copy:
      src: ./package.license
      dest: /etc/portage

  - name: update make.conf USE
    lineinfile:
      path: /etc/portage/make.conf
      regexp: '^USE='
      line: "USE=\"alsa systemd networkmanager dbus bluethooth X udev xft -bindist\""

  - name: update make.conf MAKEOPTS
    lineinfile:
      path: /etc/portage/make.conf
      regexp: '^MAKEOPTS='
      line: "MAKEOPTS=\"-j8\""

  - name: update make.conf video for lenovo 
    lineinfile:
      path: /etc/portage/make.conf
      regexp: '^VIDEO_CARDS='
      line: "VIDEO_CARDS=\"intel i965\""
    when: "{{ ansible_system_vendor == 'LENOVO' }}"

  - name: update make.conf video for lenovo 
    lineinfile:
      path: /etc/portage/make.conf
      regexp: '^VIDEO_CARDS='
      line: "VIDEO_CARDS=\"amdgpu radeonsi\""
    when: "{{ ansible_system_vendor == 'Hewlett-Packard' }}"

  - name: get cpu flags 
    shell: "cpuid2cpuflags | sed 's/: /=\"/;s/$/\"/'"
    register: cpuflags

  - name: update make.conf - cpu flags 
    lineinfile:
      path: /etc/portage/make.conf
      regexp: '^CPU_FLAGS_X86='
      line: "{{ cpuflags.stdout }}"
  
  - name: enable bluetooth
    systemd:
      name: bluetooth
      enabled: yes

  - name: update new use system
    portage:
      package: '@world'
      newuse: yes
      deep: yes
