---
- hosts: localhost
  become: true
  tasks:

  - name: update make.conf video for lenovo 
    lineinfile:
      path: /etc/portage/make.conf
      regexp: '^VIDEO_CARDS='
      line: "VIDEO_CARDS=\"intel i965\""
    when: "{{ ansible_system_vendor == 'LENOVO' }}"

  - name: update make.conf video for lenovo 
    lineinfile:
      path: /etc/portage/make.conf
      regexp: '^VIDEO_CARDS='
      line: "VIDEO_CARDS=\"amdgpu radeonsi\""
    when: "{{ ansible_system_vendor == 'Hewlett-Packard' }}"

  - name: set default options for emerge
    lineinfile:
      path: /etc/portage/make.conf
      regexp: 'EMERGE_DEFAULT_OPTS="'
      line: "EMERGE_DEFAULT_OPTS=\"--verbose\""

    #- name: get cpu flags 
    #  shell: "cpuid2cpuflags | sed 's/: /=\"/;s/$/\"/'"
    #  register: cpuflags

    #- name: update make.conf - cpu flags 
    #  lineinfile:
    #    path: /etc/portage/make.conf
    #    regexp: '^CPU_FLAGS_X86='
    #    line: "{{ cpuflags.stdout }}"

