---
- hosts: localhost
  become: true
  tasks:
  - name: managing gentoo package
    portage:
      package: "{{ item }}"
      state: present
      newuse: yes
      verbose: yes
    ignore_errors: True
    with_lines: cat packageAdditional//*| grep -v '#'
