---
- hosts: localhost
  become: true
  tasks:
  - name: managing gentoo package
    portage:
      package: "{{ item }}"
      state: present
      newuse: yes
      verbose: yes
    with_lines: cat world
  
  - name: check is chezmoi installed
    command: /usr/bin/chezmoi
    register: chezmoi_check 
    ignore_errors: True

  - name: download chezmoi 
    get_url:
      url: https://git.io/chezmoi
      dest: /tmp/chezmoi.sh
      mode: 0655
    when: chezmoi_check is failed 

  - name: execute chezmoi 
    shell: /tmp/chezmoi.sh
    args:
     chdir: /usr
    when: chezmoi_check is failed 
