---
- hosts: localhost
  become: true
  tasks:
  - name: copy package.accept_keywords 
    copy:
      src: ./package.accept_keywords
      dest: /etc/portage

  - name: copy package.use 
    copy:
      src: ./package.use
      dest: /etc/portage

  - name: copy package.license 
    copy:
      src: ./package.license
      dest: /etc/portage

  - name: update make.conf USE
    lineinfile:
      path: /etc/portage/make.conf
      regexp: '^USE='
      line: "USE=\"alsa systemd lvm networkmanager dbus pulseaudio native-headset gtk bluetooth tpm X udev uefi xft cgroup-hybrid pcre16 pcre32 unicode synaptics cairo smartcard usb cups -bindist -elogind svg printsupport git luajit minizip text device-mapper ssl ncurses pkcs7 gpg\""

  - name: update new use system
    community.general.portage:
      package: '@world'
      update: true
      newuse: true
      deep: true 

  - name: managing gentoo package
    community.general.portage:
      package: "{{ item }}"
      state: present
      newuse: true
      verbose: true
    ignore_errors: True
    with_lines: cat packageSystem/*| grep -v '#'

  - name: check is chezmoi installed
    command: /usr/bin/chezmoi
    register: chezmoi_check 
    ignore_errors: True

  - name: download chezmoi 
    get_url:
      url: https://git.io/chezmoi
      dest: /tmp/chezmoi.sh
      mode: 0655
    when: chezmoi_check is failed 

  - name: execute chezmoi 
    shell: /tmp/chezmoi.sh
    args:
     chdir: /usr
    when: chezmoi_check is failed 
