---
- hosts: localhost
  become: true
  tasks:
  - name: copy package.accept_keywords 
    copy:
      src: ./package.accept_keywords
      dest: /etc/portage

  - name: copy package.use 
    copy:
      src: ./package.use
      dest: /etc/portage

  - name: copy package.license 
    copy:
      src: ./package.license
      dest: /etc/portage

  - name: update make.conf USE
    lineinfile:
      path: /etc/portage/make.conf
      regexp: '^USE='
      line: "USE=\"alsa systemd networkmanager dbus bluetooth X udev xft -bindist\""

  - name: managing gentoo package
    portage:
      package: "{{ item }}"
      state: present
      newuse: yes
      verbose: yes
    with_lines: cat world
  
  - name: update new use system
    portage:
      package: '@world'
      newuse: yes
      deep: yes

  - name: check is chezmoi installed
    command: /usr/bin/chezmoi
    register: chezmoi_check 
    ignore_errors: True

  - name: download chezmoi 
    get_url:
      url: https://git.io/chezmoi
      dest: /tmp/chezmoi.sh
      mode: 0655
    when: chezmoi_check is failed 

  - name: execute chezmoi 
    shell: /tmp/chezmoi.sh
    args:
     chdir: /usr
    when: chezmoi_check is failed 
