---
- hosts: localhost
  become: true
  tasks:
  - name: Check if equery is available
    command: which equery
    check_mode: no
    changed_when: False
    failed_when: False
    register: gentoo_portage__register_equery
  
  - name: Install gentoolkit for equery support
    command: emerge --quiet-build=y gentoolkit
    when: gentoo_portage__register_equery.rc != 0

  - name: copy package.accept_keywords 
    copy:
      src: ./package.accept_keywords
      dest: /etc/portage

  - name: copy package.use 
    copy:
      src: ./package.use
      dest: /etc/portage

  - name: copy package.license 
    copy:
      src: ./package.license
      dest: /etc/portage

  - name: update make.conf USE
    lineinfile:
      path: /etc/portage/make.conf
      regexp: '^USE='
      line: "USE=\"alsa systemd networkmanager dbus bluethooth X udev xft -bindist\""

  - name: update make.conf MAKEOPTS
    lineinfile:
      path: /etc/portage/make.conf
      regexp: '^MAKEOPTS='
      line: "MALEOPTS=\"-j8\""

  - name: update new use system
    portage:
      package: '@world'
      newuse: yes
      deep: yes

  #- name: plugin manager vim
  #  command: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  #  become_user: blue

  - name: managing gentoo package
    portage:
      package: "{{ item }}"
      state: present
      newuse: yes
      verbose: yes
    with_lines: cat world
  
