---
- hosts: localhost
  tasks:
  - name: change shell
    become: true
    user:
      name: blue
      shell: /bin/fish

        #- name: change shell
        #  become: true
        #  user:
        #    name: root
        #    shell: /bin/fish

  - name: chezmoi init 
    shell: chezmoi init https://github.com/bluehack42/dotfiles.git 

  - name: chezmoi apply 
    shell: chezmoi apply 

  - name: add matplotlib python extension
    pip:
      name: matplotlib
      extra_args: --user
