---
- hosts: localhost
  tasks:
  - command: /usr/bin/chezmoi
    register: chezmoi_check 
    ignore_errors: True

  - name: download chezmoi 
    become: true
    get_url:
      url: https://git.io/chezmoi
      dest: /tmp/chezmoi.sh
      mode: 0655
    when: chezmoi_check is failed 

  - name: execute chezmoi 
    become: true
    shell: /tmp/chezmoi.sh
    args:
     chdir: /usr
    when: chezmoi_check is failed 

  - name: change shell
    become: true
    user:
      name: blue
      shell: /bin/fish

  - name: chezmoi init 
    shell: chezmoi init https://github.com/bluehack42/dotfiles.git 

  - name: chezmoi apply 
    shell: chezmoi apply 

  - name: install vim plug 
    shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim' 

  - name: update vim plug 
    shell: nvim '+ PlugInstall --sync' +qall &> /dev/null < /dev/tty 
